### ISSUE TITLE
Domain transfer ...

### ISSUE THREAD

**Issue by bennibu** [foodcoops/foodcoops.net#36]
Right now, foodcoops.net is owned by about:source and now we wanna get rid of all legacy projects I brought the company. The domain foodcoops.net and some email inboxes (support, webmaster) will be soon deleted (starting with deleting of all inboxes).

Please [get in contact with me](mailto:benjamin.meichsner@aboutsource.net) and I will send you the domain transfer codes.

Best,
benni

**Comment by 1resu** [comment]
Sense.Lab can become the new owner of the domain. Just say so if everybody is ok with it.

**Comment by JuliusR** [comment]
> Sense.Lab can become the new owner of the domain

In my opinion, that is the best solution.

What do you @arouel, @paroga, @wvengen think?

**Comment by 1resu** [comment]
There are one real mail box (support) and two virtual addresses (foodsoft and webmaster) for this domain. Do we want to redirect the incoming messages of all three addresses to our support list?

**Comment by paroga** [comment]
nice @bennibu created many admin accounts on old installation with support@foodcoops.net and people did not delete / deactivated those accounts there might be a lot of internal messaging of foodcoops on this address. Maybe we can check that first with a separate list first before switching to our real support list.
Might be a reason to contact the foodcoops on the Austrian server about that issue ;-)

BTW: do we have access to the DNS entries already? I'd like to swich to GitHub pages directly for our root domain. The generated page point to foodcoops.github.io instead of foodcoops.net, because of this configuratiion issue and there is no need to provide a reverse proxy ourself.

**Comment by paroga** [comment]
i've updated the Austrian instance. could somebody check the `users` tables on the `foodcoops.net` server for that address?

**Comment by 1resu** [comment]
> do we have access to the DNS entries already?

The domain transfer took place and we are now in control of the dns entries.

**Comment by paroga** [comment]
If you all agree I'd like to move `foodcoops.at` and `www.foodcoops.at` to GitHub page. Could someone with access change the DNS entries according to [documentation](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)?

**Comment by 1resu** [comment]
> Maybe we can check that first with a separate list first before switching to our real support list.

I just created a new mailing list. All messages from the three old foodcoops.net addresses will be forwarded to it.

**Comment by JuliusR** [comment]
> The domain transfer took place and we are now in control of the dns entries.

Let us close here because that was the main point of this issue. :tada: 

> i've updated the Austrian instance. could somebody check the `users` tables on the `foodcoops.net` server for that address?

I just checked that there are still 4 instances with that user. Let us address that in #47 and #48.

> BTW: do we have access to the DNS entries already? I'd like to swich to GitHub pages directly for our root domain. The generated page point to foodcoops.github.io instead of foodcoops.net, because of this configuratiion issue and there is no need to provide a reverse proxy ourself.

I do not fully understand your suggested solution. It might be due to the language barrier. I suggested my favorite solution here: #49.

> If you all agree I'd like to move `foodcoops.at` and `www.foodcoops.at` to GitHub page. Could someone with access change the DNS entries according to [documentation](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)?

Sorry @paroga, but I do not fully understand what you would like to do. Could you please open a new issue if that is still relevant?
